name: Deploy Espri.Fashion Main

on:
  workflow_call:
    secrets:
      PROJECT_ID:
        required: true
      SA_EMAIL:
        required: true
      WIF_PROVIDER:
        required: true
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Log GitHub Actions Secrets
        env:
          SECRET_USER: 123
        run: |
          echo "ID: $SECRET_USER"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install GCP CLI
        uses: google-github-actions/auth@v2
        with:
          project_id: '${{ secrets.PROJECT_ID }}'
          service_account: '${{ secrets.SA_EMAIL }}'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest -f build/Dockerfile .

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./scripts/git_update.sh -v minor

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag $IMAGE_NAME:latest europe-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest europe-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
