name: Deploy Espri.Fashion Main

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      id-token: write
    environment: GCP WIF
    env:
      IMAGE_NAME: espri-backend-main
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install GCP CLI
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account: ${{ secrets.SA_EMAIL }}
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest -f build/Dockerfile .

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./scripts/git_update.sh -v minor

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag $IMAGE_NAME:latest europe-west1-docker.pkg.dev/$PROJECT_ID/espri-main-service/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest europe-west1-docker.pkg.dev/$PROJECT_ID/espri-main-service/$IMAGE_NAME:$GIT_TAG
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/espri-main-service/$IMAGE_NAME:latest
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/espri-main-service/$IMAGE_NAME:$GIT_TAG

      - name: Deploy to GCP Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        with:
          service: espri-backend-main
          region: europe-west1
          image: europe-west1-docker.pkg.dev/$PROJECT_ID/espri-main-service/$IMAGE_NAME:$GIT_TAG
